### PR TITLE
Supply a data-url param so that we don't leak out the custom URLs for…

### PR DESCRIPTION
**Pull request by misteranderson**
… the signup confirmations in the tweets.

 Changes to be committed:
	modified:   thanks-driver/index.html
	modified:   thanks-rider/index.html

### CODE REVIEW

**Comment by misteranderson** [comment]
Fixes issue #207

**Comment by langdonms** [comment]
@misteranderson Looks good to me, though I don't think I have merge permissions

**Comment by richardwestenra** [comment]
wait a sec, I think I already fixed this

**Comment by richardwestenra** [comment]
@misteranderson Yeah I fixed this already #197 (the original issue was #194).

**Comment by misteranderson** [comment]
As we discussed on Slack, the fix for #197 does not touch the 2nd set of twitter buttons shown below "Let your friends know".

**Comment by richardwestenra** [comment]
You're right, I foolishly jumped to wrong conclusions. This is great, thanks!

**Pull request merged**
