### PR TITLE
Refactor homepage form JS to improve readability and documentation

### PR DESCRIPTION
**Pull request by richardwestenra**
# Description
This is a major PR, but shouldn't change any functionality. I've gone through all the JS in main.js (the script that runs all the homepage form logic) and refactored it and added extensive JSDoc comments, to make it more accessible to newbie developers.

# Development notes
The only significant functionality change is that I've rewritten the date fallback functionality to only run on form submit instead of every time you change one of the inputs. Once I broke things down a bit better I was able to see that the way it was written before probably should not have worked, because it would only update the most recently edited value and would leave the others set to today's date. I don't think anyone had noticed this bug yet because it's only in effect on older browsers. Anyway it should be fixed :)

# Review notes
This should be ready for review now. It's a fairly hefty review though, so unless you feel like going through all of it line by line, it might be easier to just test the forms to check that nothing has broken.

### CODE REVIEW

**Comment by richardwestenra** [comment]
@jkbits1 @dmilet @langdonms Any chance of a review/test/approval on this PR, anytime soon? I'm nervous about complicated conflicts the longer it's left open.

**Comment by dmilet** [comment]
My technical expertise in JS is not sufficient to confudently said it's all right

**Comment by jkbits1** [comment]
@richardwestenra I gave it a quick look when it was raised, but like you say, it's large and there aren't any specific tests for it. Clearly, it all sounds generally useful, so later today I'll run it, do some standard tests, and if that goes ok I'll merge it. We can deal with any issues that haven't been spotted as they occur.

**Comment by jkbits1** [comment]
@richardwestenra tested ok, merged 👍

**Comment by richardwestenra** [comment]
@jkbits1 Great, thanks! :)

**Pull request merged**
