### PR TITLE
Develop calendar

### PR DESCRIPTION
**Pull request by sfirrin**
Makes a calendar and time slider for adding dates and time ranges to a list of available dates and times

### CODE REVIEW

**Comment by sasjkia** [comment]
Hey there - thanks a lot, I think this works very well! :) 

I was actually also thinking that this would be good to incorporate into forms for drivers and riders on the live site as soon as possible, so we can start collecting these data.

Do you think you could also get the remove button to work?

**Comment by sfirrin** [comment]
Glad to hear you like it!

Yes, definitely, that shouldn't take more than a couple hours. I have a big assignment due tomorrow so I can't work on it right away, but I'll be able to do it after that.

**Comment by sasjkia** [comment]
Thank you! Hope the assignment goes well! :)

**Comment by sasjkia** [comment]
Thanks @sfirrin these look great! this is def the most intuitive interface :) Next steps for this is to ensure that people can't input unavailable dates / times. All of these outlined in issue #18

**Pull request merged**
