### PR TITLE
Rider form updates 2

### PR DESCRIPTION
**Pull request by richardwestenra**
## Description

Fairly basic PR, mainly just adding ‘Preferred Method of Contact’ checkboxes, as requested in issue #96. I've also added some JS to only require the rider's email address if Email is selected as a preferred contact method.

## Development notes

This PR is branched off of #120 (which has already been merged), hence the extraneous commit history. Only the last two commits are relevant, the rest has already been merged so ignore it please. I could merge master into this branch to clean it up, but it’s probably not worth the extra commit - we might as well just ship it as is, yeah?

### CODE REVIEW

**Comment by richardwestenra** [comment]
@dmilet @jkbits1 Can you please confirm that these new form fields (`name="RiderPreferredContact"`) won't break anything on the back end?

**Comment by dmilet** [comment]
Yes, I'd say it is safe to merge. The node app currently does not recognize this field, so it will be ignored. I'll work with @jkbits1 to update the DB to support the new field. The existing field RiderPreferredContactMethod might not be large enough to support multi-values (it seems strange to me, "prefer" means one selection amongst many). I wonder how the data will be received by the node app, will values be concatenated, or comma-separated ?

**Comment by richardwestenra** [comment]
ok thanks @dmilet, I might just go ahead and merge it then.

Yeah 'preferred method' sounds a little strange to me, as well, probably because it implies a singular. This is really 'preferred method(s)', but I don't think it really matters much?

When I tested it earlier, it sent each as a separate key/value row, with duplicate keys:
```
RiderPreferredContact:Email
RiderPreferredContact:Phone
RiderPreferredContact:SMS
```
Will that be ok?

**Comment by dmilet** [comment]
I don't know enough about node application to tell. I'll let @jkbits1 comment. I think on the database side, we'll have to save comma-separated or pipe-separated values, so it will require some formatting from the node app.

**Comment by dmilet** [comment]
Yes, go ahead an merge.

**Pull request merged**
