### PR TITLE
Refactor datetime formatting

### PR DESCRIPTION
**Pull request by richardwestenra**
Make the form button and time formatting JS a lot simpler and DRYer.

**Note:** This PR is on hold for the moment while we verify that it works properly. It may need some additional testing to ensure that it doesn't break anything.

### CODE REVIEW

**Comment by jkbits1** [comment]
@richardwestenra hi thanks for this

when I run locally I get an "invalid time value" in the map on line 735. I see you have taken out the (rather yucky but necessary!) explicit year addition. Does it relate to that ?

I also patched the code here re midday times. Is this handled in the refactored code?
https://github.com/voteamerica/voteamerica.github.io/pull/115/files

**Comment by jkbits1** [comment]
@richardwestenra one thing this project is short on is tests. This date code particularly would benefit from tests as it is very easy to introduce errors when refactoring due to edge cases, etc. I'm not free to set anything up, but if something existed, I would be happy to add tests to it

**Comment by richardwestenra** [comment]
@jkbits1 Thanks a lot, this is very valuable.

1. I haven't encountered this bug, but I'll look into it.
2. I might have overlooked that midday bugfix. It's not clear to me exactly what the bug is but I'll look into it. What's the easiest way to replicate it?
3. Yes we definitely need tests, good point! If we move this JS to an external file (which I've been meaning to do when I get a chance) then it'll be easier to commit. Will do in a future commit?

**Comment by jkbits1** [comment]
@richardwestenra great. I don't think this date handling code has completely settled yet so any refactoring may need to be changed again later

**Comment by richardwestenra** [comment]
okay bugs 1 and 2 should be fixed now.

**Comment by jkbits1** [comment]
Line 735 generates this "Thursday, Oct 2708:50:00". I should be working with your latest code, let me know if not :smile:

**Comment by richardwestenra** [comment]
@jkbits1 Argh, I forgot to test when changing the dates! Good catch. Sorry, I was in a hurry. Fixed.

I really need to sort out some tests asap. Soon!

**Comment by jkbits1** [comment]
ah, that works better...

I think it might be storing the time as local time (e.g. 10am) but with the 'Z' at the end of the string that is in fact 9am UTC. let me know if that seems incorrect to you. moment was handy for making these issues go away and giving us other options later on depending on how the whole time storage discussion pans out :smile:

**Comment by richardwestenra** [comment]
Closing this branch because this work is superceded by the work on V2 of the Availability Date/Time List.

**Pull request closed without merging**
