### PR TITLE
update additional rider information text, position list to right of input

### LINKED ISSUE #305: Move "I can only communicate in a language other than English" to the notes bullets
We do not want to make more updates to the database and this format doesn't allow for the user to be specific about the language, so we cannot have this extra feature that has just been added.

- [ ] Please remove the "I can only communicate in a language other than English." check box.
- [ ] Instead, add the same sentence as a bullet point under "Other requirements".
- [ ] Please change the final "Etc." bullet in this list to "Other".
- [ ] Please move all of these bullet points next to the box, rather than underneath

Thank you! :)

### PR DESCRIPTION
**Pull request by russon77**
## Motivation

Resolves #305 

## Changes

- [x] moved and updated text
  - i did not think that the text wording was quite right, so i changed it - happy to revert the changes
  - also updated the placeholder
- [x] changed how the list was positioned
  - now `inline-block`, so the list appears to right of input on larger screens

### CODE REVIEW

**Comment by sasjkia** [comment]
I like the look of this, and think it's ready to merge now.

@kylejcrawford  for future versions, was there also talk of updating the text inside the actual box?

In any case, it would be good to have this version live this weekend, for the election and the demo on Tues.

**Comment by richardwestenra** [comment]
@sasjkia The screenshot is my suggestion, it's not showing how the PR currently looks.

@russon77 Let me know whether you want to make that change or whether I should just go ahead and merge.

**Comment by russon77** [comment]
@richardwestenra i added the spacing between the two elements :+1: for "pushing down", though, i fear my css-fu is insufficient - so feel free to merge! :fireworks:

**Comment by richardwestenra** [comment]
@russon77 No worries, I had trouble with that too! Probably an inline-block vertical-alignment thing. I used `position:relative` & `top` to move it down, but that's a little hacky. Anyway, sounds good, thanks for this!

**Comment by kylejcrawford** [comment]
I think this looks great. @richardwestenra @russon77 Would it be fairly simple to update the text within the box?

**Comment by richardwestenra** [comment]
@kylejcrawford Yes, should be very simple. Add it to an issue (or create a new one) if you have a request.

**Pull request merged**
