### PR TITLE
Convert site to run on Jekyll

### PR DESCRIPTION
**Pull request by richardwestenra**
# Description

This is a **major PR** to convert the entire front-end to run on [Jekyll](https://jekyllrb.com/). Jekyll is a Ruby-based static site generator, which is natively supported by Github Pages. This has been a goal of mine for some time, because we’ve had issues in the past with contributors failing to propagate their changes sitewide. Jekyll’s support for templating will help fix this.

## Pros:
- It will allow us to use templating, so we can avoid HTML duplication, which will make future sitewide HTML changes easier
- It will allow us to customise permalinks, so we can put all of our HTML page templates in the same folder, which will keep things tidier
- No need to change the deployment process: The site will be generated and deployed automatically every time we push to master, as it is currently.
- Includes Markdown support, should we need it.

## Cons:
- To work on the site locally, you’ll need to have Jekyll and Ruby installed on your machine.
- Slightly increased barrier to entry for newbie devs. However this will only exclude those who are only able to handle plain HTML/CSS and have never used the command line, which is hopefully not too many, given that people are contributing to an OSS project on Github.

# Development notes

- I've extracted header, nav, and footer to partials so they can be reused 🎉. I've added conditional logic to show/hide any code which differed from pages to page (see nav and footer links, for example).
- I've moved all of the HTML page templates into a new 'pages' directory to keep things organised, and am using a custom 'permalink' frontmatter variable to handle routing, instead. This should make pages easier to work on because they're no longer all called index.html.
- I've added a somewhat convoluted 'baseurl' partial template to generate a base url variable for any asset filepath, so that we can still use relative urls to assets (so that the site will still work on subdirectories etc without modification). It seems to work fine. It won't work for very deeply nested pages but we haven't got any of those at the moment, and we can always extend it further if necessary.
- There was a request from @dmilet to have an option to generate the page for a given target API URL:
    > Right now, the page points to /live, but if we need to support demos, we'll want to use a different page that points to a different API URL, /demo for example. 
    
    Hence I have added an alternative config file on that can optionally be served when running the site locally, by running `jekyll serve --config _config.yml,_config-dev.yml` (instead of `jekyll serve` which just serves the standard live environment).
- Jekyll also supports other cool stuff like Sass and plugins, and at some point we might want to convert the CSS to Sass and add plugins and extend the functionality, but for now I think this is enough.
- I realised after finishing the conversion that this is totally going to break the existing outstanding PRs. Oh well. I'll need to fix their merge conflicts and implement them next, because I'm sure there's worthwhile stuff in there.

### CODE REVIEW

**Comment by jkbits1** [comment]
@richardwestenra great! I'm keen to try this out in docker sometime, just let me know when you think it's ready

**Comment by richardwestenra** [comment]
Sure, feel free to try it out. I think it's pretty much ready, I'm just not
100% sure, and I won't have time to confirm until Monday night.

It should be in use on my github pages fork at
richardwestenra.com/voteamerica.github.io

**Comment by jkbits1** [comment]
@richardwestenra this looks good 👍 I've tested using jekyll serve with both the default config and and config-dev.yml files. At the moment, these tests have only been for serving up local pages, but the templates vars are working. 

Assuming that we check how this fits in with current priorities, schedules and system demos, I'm happy for this to be merged and work from here (assuming your own checks pass). Let me know if you want me to merge it sometime

**Comment by richardwestenra** [comment]
Sure, thanks! I should be able to do a final check on Monday night.

**Comment by richardwestenra** [comment]
@jkbits1 okay I think this is now ready to merge! 🚢

**Comment by jkbits1** [comment]
@richardwestenra great 🎉 it looked fine last time but I'll test it again. It adds a lot of benefits so I'll merge it unless there is a major issue, and anything minor can be patched. 

Regarding it being a barrier to entry, I'm using docker successfully to test and use it. The relevant files will be added to the repo, so that will be an option for those devs

**Comment by jkbits1** [comment]
@richardwestenra this works really well 😄 Good point about the footers! I'm trying to get a local end-to-end test running and if I see any related errors I'll create an issue.

I'd like to create a PR for the redirect value (thanks-rider/driver/helper). Any objections or do you prefer to make this change yourself?

**Comment by richardwestenra** [comment]
@jkbits1 Thanks! Regarding the redirect values, I'm not sure I follow you. Do you mean the same as in [this commit](https://github.com/voteamerica/voteamerica.github.io/pull/200/commits/c658ed3b441fbc8032e26f1fb6505edf6c0822d1) in one of the open PRs?

**Comment by jkbits1** [comment]
@richardwestenra no problem! That's the right value but I'd like to make the `http://carpoolvote.com` part flexible based on the config file. The same key `api` should be fine

**Pull request merged**
