### PR TITLE
faq page created

### LINKED ISSUE #191: Create FAQs
These will free time spent responding to the same email questions and provide driver, riders, and partners with the basic info they need to use the platform:

https://docs.google.com/document/d/1Tf4jDAWSyqvBrSYxjFtTa_gjJrZ3Ti3b7tZlujQbGgY/edit?usp=sharing
- [x] Create a page dedicated to FAQs.
- [ ] Include a link to these right above the Terms and conditions in the footer (in the same format). Also include.
- [ ] Include another link to these on the "How does it work?" page, once its live.

### PR DESCRIPTION
**Pull request by moinshaikh**
New page : faq.html created with FAQs.

Fixes #191.

### CODE REVIEW

**Comment by sasjkia** [comment]
thanks for doing this @moinshaikh!

a few things have changed since this was written. Please could you amend the following:
- [ ] Please delete: "If someone lets us know that they are a senior or have a disability, we try to match them with drivers who have been introduced to us by our partners (who have done their own checks on the drivers). This may not always be possible in every zip code. If there is another driver – who is not affiliated with one of our partners – but is otherwise a near-perfect fit, they may also be matched with a vulnerable rider." (we've removed this check box)
- [ ] Please fix type: "Our volunteers care passionately about empowering you to do but but the decision is ultimately up to you!": Change the first "but" to "this"
- [ ] At the end of the last question ("Do you have an app"), add: "Riders can choose receive updates on their request status via SMS, if they don't have regular access to the internet."

**Comment by sasjkia** [comment]
I also have a few more that have been coming through since more people have been signing up. give me a sec.

**Comment by sasjkia** [comment]
More FAQs:

- [ ] I am receiving ride requests outside of the radius or time that I specified _[add directly underneath "One of the riders on the map..." answer in existing FAQs]_ 

We've found that some drivers and riders are happy to be a little flexible with time or place, once they realize that someone needs or can give a ride. Sometimes, we send drivers notifications for matches that are a little out of their date or time range, just in case they can still make it.

If you signed up up to or before November 5, the offers you receive may be a little less sensitive to location and you may receive offers for up to 100 miles from where you are.

If this is the case, and you would like to receive notifications for rides a closer to the radius that you signed up for, simply pause (NOT cancel) notifications for your current ride offer, then sign up again using the same details. This will preserve any matches you've already accepted, while making new notifications more location-sensitive.

- [ ] I'm having trouble using the self-service portal. What should I do? _[add directly underneath "How can I manage my rider request" answer in existing FAQs]_

The email notifications you receive will contain all of the information you need to manage your matches.

Drivers can use the links in these emails to:

- Accept a ride request
- Cancel an accepted match
- Stop receiving notifications for the current driver offer
- Cancel the entire driver offer

Riders can use the links in these emails to:

- Cancel an individual match with a driver
- Cancel the entire ride request

If you're unable to manage your ride offer or request using both the self-service portal and email notifications, please email support@carpoolvote.com.

If you are unable to use the internet, please SMS or phone us on 804-239-3389 and we'll try to help.

- [ ] I need to change the details of my signup. How can I do this? _[make this the 2nd point in the existing FAQs]_

The easiest way to change the details of your signup is to pause (NOT cancel) notifications for your current ride offer or request, then sign up again using the same details. This will preserve any matches you've already accepted, while new notifications will have the updated details.

**Comment by sasjkia** [comment]
thanks @moinshaikh!!!

**Comment by sasjkia** [comment]
slightly updated the text of the final bullets

**Comment by moinshaikh** [comment]
Ok am implementing this feedback.

**Comment by sasjkia** [comment]
great - thanks! just made a final tweak to the last bullet

**Comment by sasjkia** [comment]
Some more - apologies, these keep coming in :)

- [ ] I have received a proposed rider match. Does that mean I need to drive them?
A match is only confirmed once a driver has accepted it. If you cannot make the ride for whatever reason, you do not have to do anything. The match will be confirmed for the first driver who accepts it.


- [ ] What happens if I cancel a confirmed match?
If you are a driver, cancelling a confirmed match means you will no longer complete the journey. The rider will then have to wait for another driver to accept their request.


If you are a rider and you cancel a confirmed match, you will no longer have a confirmed ride. You will have to wait for another driver to accept your ride request. We cannot guarantee that you will find another ride if you have cancelled an accepted match.

- [ ] What happens if I cancel my ride offer or request?
All of of your confirmed matches will be canceled and you will no longer receive any notifications. Only use this option if you are certain that you no longer want to give a ride to anybody - including your existing matches - or you no longer need a ride.

**Comment by sasjkia** [comment]
have a look at the google doc for locations for these:
https://docs.google.com/document/d/1Tf4jDAWSyqvBrSYxjFtTa_gjJrZ3Ti3b7tZlujQbGgY/edit?usp=sharing

**Comment by sasjkia** [comment]
could we please replace the text of this point with the following:
Can you guarantee that I’ll be matched with a driver / rider?

We can only propose a match a rider match to drivers who are a good fit for the time, location, and seating / accessibility needs of the rider. Drivers can then choose to accept a match if it works for them. We are unable to ensure that drivers and riders will meet each other’s criteria.


We have done our best to test the system and to ensure that it works the way it’s supposed to. Our testing has not revealed any issues that could prevent the system from finding potentially suitable matches - provided user details have been entered correctly. At the same time, we have not had the opportunity to test the system at scale.


So, we encourage both drivers and riders to use the platform as one way to complement their other  efforts to give or get a ride.


We also encourage local people and organizations to help us promote the project. The more people there are who know about our service in the same area, the more likely it is that a voter will be matched with a driver and so be able to claim their vote!

**Comment by moinshaikh** [comment]
Fine, so can I assume the latest doc (https://docs.google.com/document/d/1Tf4jDAWSyqvBrSYxjFtTa_gjJrZ3Ti3b7tZlujQbGgY/edit) has all the updated questions/answers?

**Comment by sasjkia** [comment]
yes! :)

Warm wishes,
Sasjkia

FOUNDER AND ORGANIZER
[image: CarpoolVote.com] <http://carpoolvote.com/>

<https://www.facebook.com/CarpoolVote>    <https://twitter.com/CarpoolVote>
  <https://www.youtube.com/channel/UCY1aS3TMDGxVbckA7Va0QFA>

sasjkia@carpoolvote.com | 347-453-7873

**Comment by sasjkia** [comment]
yes! apologies for being a bit of a pain about these.

**Comment by moinshaikh** [comment]
No problem at all :)

**Comment by richardwestenra** [comment]
Once the text changes are done, could you please move the page to `/faq/index.html`, and include a link to `/faq` in the footer?

**Comment by moinshaikh** [comment]
@richardwestenra yes I will do it. :)

**Comment by moinshaikh** [comment]
I am done with FAQ changes. Have created new faq page under faq/index.html

I am adding FAQ link on footer on other pages.

**Comment by richardwestenra** [comment]
Hey you did the thing again with adding a PR to the wrong repo. No need to create a new PR, just add a new commit to this branch and it will be added to this PR.

**Comment by sasjkia** [comment]
thanks @moinshaikh. i can't see the latest changes i requested?

**Comment by moinshaikh** [comment]
Sorry,

You mean to *Commit directly to the master branch. ?*


*[image: Inline image 2]*

**Comment by richardwestenra** [comment]
@moinshaikh Yeah to `moinshaikh:master`, the branch that this PR was created from.

**Comment by richardwestenra** [comment]
@moinshaikh Perfect, thanks. Can you please delete faq.html?

Idl whether you're using the command line, but for future reference, if you use `git mv faq.html faq/index.html` to move the file then it preserves the git history for that file.

**Comment by moinshaikh** [comment]
Thank you.

Deleted faq.html

I was using web version / interface of GitHub but I heard from many (and seen from you) that managing stuff from command line is easier, so I would be using it for all future work.

Thanks again for kind help.

**Comment by sasjkia** [comment]
thanks @moinshaikh! looks like the branch has some conflicts...

**Comment by richardwestenra** [comment]
@moinshaikh Are you able to fix your merge conflicts yourself? Sorry I'm unable to.

**Comment by richardwestenra** [comment]
okay I'm taking this over to get it merged. Thanks @moinshaikh for your work on it!

**Pull request closed without merging**
