### PR TITLE
Added Terms & Condition page, its link, checkboxes (#161) in both forms and How It Works page (#153).

### PR DESCRIPTION
**Pull request by moinshaikh**
In this PR, I've added link to Terms & Condition page in both Rider and Driver forms. I have also added checkboxes as requested in Issue #161. All the 3 points mentioned in the Issue are done with this PR.

### CODE REVIEW

**Comment by pavsaiprasad** [comment]
@Carmenego This PR also contains fix for #183 in addition to #153 and #161.

**Comment by sasjkia** [comment]
@jkbits1 @dmilet is sms live now? if so, driver email can be optional. otherwise, needs to be mandatory so they can receive notifications.

**Comment by jkbits1** [comment]
sms handler works, don't know about it's current deployment status

**Comment by sasjkia** [comment]
ok, it looks to me like email address can be optional if we like

**Comment by sasjkia** [comment]
The 3 paragraphs of t&cs are repeated. we only need the one check box including the three paragraphs. this replaces the multiple tick boxes.

Please could this one be dealt with as a matter of urgency? Lots of people are signing up and they need to agree to the full 7&cs doc.

**Comment by moinshaikh** [comment]
@sasjkia Okay, I got it. I am working on this on priority basis.

**Comment by moinshaikh** [comment]
@sasjkia I have removed repeated text as per your comment.
Can you please review the PR and advise me if all good now.
Thanks

**Comment by richardwestenra** [comment]
Thanks @moinshaikh. There's a conflict that's preventing us from merging this branch. Can you please try to resolve it? You'll probably need to merge master. 

If you need help, let me know and I'll see what I can do.

**Comment by moinshaikh** [comment]
It'd great if you can help here. I see the conflict notice but didn't get what's actually conflicting. 

image

**Comment by sasjkia** [comment]
Any news on this? It would be really nice to get people signing up to agree to the T&Cs!

**Comment by moinshaikh** [comment]
Hello, I was waiting for someone from you to comment/assist on this as I could not find the exact conflict/issue. I checked and could not see what is actually conflicting. Can someone look into this conflict issue and let me know if something needs to be done from my side.
Thanks.

**Comment by richardwestenra** [comment]
Sorry Moin, I've been slack about responding because I've been pretty busy and didn't really know what to tell you. Fixing a merge conflict can be tricky, I don't think I'll be able to easily talk you through it via comments on here. Basically, you'll need to pull the most recent changes from the remote master branch, and then go through and fix any conflict that Git highlights. I just did a quick google, here are some guides about how to do this:
- https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/
- https://www.git-tower.com/learn/git/ebook/en/command-line/advanced-topics/merge-conflicts
- https://githowto.com/resolving_conflicts

If you get completely stuck, I can try to fix it myself for you if you like - either by making a pull request to your branch, or by closing your PR and making my own. Let me know!

**Comment by moinshaikh** [comment]
Hi Richard, many thanks for your support. I would really appreciate if you can help me this time by making PR or if you wish you can close my PR and open yours. am fine with either way. I tried to refer to the links but since this particular PR has many other changes, I feel lost and wasting our time. So if you can take this up for this time please.

Thanks again,
Moin

**Comment by richardwestenra** [comment]
No worries, will do. Thanks Moin!

**Comment by richardwestenra** [comment]
Hey @moinshaikh! Just saw you add a new commit. Please create separate branches for each new pull request, otherwise you'll be adding your new commits onto this PR. It also just helps keep things sensible.
Try this: http://nvie.com/posts/a-successful-git-branching-model/

Assuming that ‘upstream’ is the original remote repo, and ‘origin’ is your forked remote repo, and ‘local' is your local clone of your forked remote repo, then your typical git workflow should look something like this: 
`upstream/master` --(pull)--> `local/master` —(checkout)--> `local/feature-branch` —(push)--> `origin/feature-branch` —(submit PR)--> `upstream/master` --(and repeat)—> …...

**Comment by moinshaikh** [comment]
I got it. That is why my previous work was going under same PR. Thank you for helping me understand this. I am sorry to bother you again and again though. I will keep this point noted.

**Comment by richardwestenra** [comment]
👍 great, no worries 😄

**Comment by richardwestenra** [comment]
@moinshaikh One more thing: Could you please ensure that any future pages are created at `/page-name/index.html` instead of `page-name.html`? This is a URL styling format that I've been trying to follow. I understand that the instructions haven't always been clear, and I should've clarified this with @sasjkia. It's my fault, I apologise.

**Comment by moinshaikh** [comment]
No worries, noted. Thank you for clarifying.

Moin.

**Pull request closed without merging**
