### PR TITLE
Redesign self-service page

### LINKED ISSUE #185: No submit button on the self-service page
hey, just got the below message. what's the status of self-service?
"Good morning:

I signed up last night, but when I click the link to manage my rides, I enter my info, but there is no button to click to send it through.

Please advise.

Thanks.

Suzanne"

### PR DESCRIPTION
**Pull request by richardwestenra**
## Description

When you arrive on the self-service page, it presents a login form. It asks for your reference, phone number, and user type. If you have the `type` and `uuid` query string keys populated, then it will hide those fields. 
Once you've logged in, you'll probably only see the 'cancel' button, unless the 'score' query string field is populated. The other buttons are works in progress, afaik.

Fixes #185.

## Development notes

I've added jQuery and used tinyQuery for a lot of the query string functionality
## Screenshots

image
image
image

### CODE REVIEW

**Comment by jkbits1** [comment]
The link in the SMS (presumably the email, too) provides the querystring param as uuid_driver (the spec defines this a s UUID_driver but the lack of capitals may not be a problem). When I accessed the page with this param the login fields were shown anyway.

I entered the uuid and phone no in the fields and clicked login. The Cancel Drive Offer button was shown, but not the button to accept a match.

**Comment by richardwestenra** [comment]
@jkbits1 Okay thanks, good to know. The form redirect and email both use the 'uuid' field. I haven't received any SMS messages.

Ideally it'd be good to be consistent. In the meantime, I'll update it so that if `uuid_driver` or `uuid_rider` are set then it sets the `uuid` and `type` values.

**Comment by richardwestenra** [comment]
@jkbits1 Ok I've added better support for `uuid_driver` and `uuid_rider`.

Btw, it will show the other buttons (e.g. "Cancel Drive Offer"), but only if you have the 'score' query string field populated. This is required to submit these buttons anyway.
Looks like there's a small bug with this though, which I'm just fixing.

**Comment by jkbits1** [comment]
@richardwestenra great, let me know when it's ready to test :+1:  the use of uuid_driver and uuid_rider is consistent across all possible uses of the page. For buttons that require both driver and rider uuid it is necessary to have the information on which uuid is which in the name itself. For the cases where only one uuid is needed, the querystring name remains the same.

**Comment by richardwestenra** [comment]
@jkbits1 Should be ready to test now afaik.

So for situations where the user needs the Score, UUID_Driver and UUID_Rider qs value populated, where do they come from? Because I haven't encountered this in form redirects nor emails, and it sounds like links aren't working properly on SMS, and there isn't an API endpoint we can query to get this information (or if there is then I don't know about it).

**Comment by jkbits1** [comment]
@richardwestenra great, will test this shortly. The querystring links (Score, UUID_Driver and UUID_Rider) are definitely provided by the sms messages and presumably the email messages, too (not my area to check). Happy to look at anything to study this further

**Comment by richardwestenra** [comment]
@jkbits1 okay thanks. The emails I've received have only included uuid, e.g. `http://carpoolvote.com/self-service/?uuid=b409c43a-b581-4a5c-831d-339c1783c8a9`

**Comment by jkbits1** [comment]
@richardwestenra I made some comments (and requests for some quick checks) in the related issue  https://github.com/voteamerica/voteamerica.github.io/issues/198#issuecomment-257591046

**Comment by misteranderson** [comment]
@jkbits1 @richardwestenra Any reason this should _not_ be merged ASAP?  This should resolve many of the complaints that users had raised.

**Comment by richardwestenra** [comment]
None afaik. @jkbits1 sounds like he still has reservations but I don't really understand what they are.

**Comment by richardwestenra** [comment]
I'm tempted to suggest we merge this now and fix any outstanding problems in a future PR? I don't think there's any existing functionality broken by this PR.

**Comment by misteranderson** [comment]
I concur.  This fixes more issues than it causes; Let's get it in place and deal with the next set of changes.

**Comment by jkbits1** [comment]
@richardwestenra can you just check it against the test db, please? More details are in my comment above (it links to my comment on the related issue). I've made some changes to the test db, and if this works they need to be applied to the live db

**Comment by sasjkia** [comment]
Just had a look at the self-service landing page. Really awesome to see progress with this!

Could I check, are drivers and riders also now able to cancel individual confirmed matches?

**Comment by jkbits1** [comment]
@sasjkia good question. What has the testing shown up?

**Comment by richardwestenra** [comment]
@sasjkia @jkbits1 No, because there's no way to get a list of matches that would provide the necessary information to cancel one.

**Comment by sasjkia** [comment]
@richardwestenra  @jkbits1 - @dmilet has already included the "reject match" function in notifications.

**Comment by sasjkia** [comment]
@richardwestenra i thought i'd already seen a mockup for this from you? (i had some queries about the language)

**Comment by richardwestenra** [comment]
@sasjkia If we get it working from email only or for sms only then that doesn't help users who visit from other means (e.g. from the thank you page, or direct link). If we get it working on login without needing to follow an email link then it will be usable for everyone. However at the moment that's impossible without an additional API endpoint, which was apparently never included in the spec. I am unable to do this myself, it needs back end work. I am unable to edit the spec. My hands are tied here.

idk what you mean about a mockup, sorry.

**Comment by sasjkia** [comment]
@richardwestenra i was asking what's the difference between the 2 buttons next to each other (that had similar wording)

**Comment by sasjkia** [comment]
@dmilet would you be able to advise?

**Comment by sasjkia** [comment]
@richardwestenra @jkbits1 so what do people see at the moment when they log into self service?

**Comment by richardwestenra** [comment]
Try http://richardwestenra.com/voteamerica.github.io/self-service/?type=rider&uuid=3077bd71-3149-4c6d-b9f3-12607f92513b
or try http://richardwestenra.com/voteamerica.github.io/self-service/?type=driver&uuid=1234567890 (fake uuid)

There are two types of cancellation: Cancel match and cancel everything.

You can see the match buttons, but they don't work because there are no matches to cancel.

The overall cancel button should work, it doesn't seem to. But then I never got it working before either so idk whether anything has changed. I haven't made any real changes to its functionality.

@jkbits1 You can see the data available on a given page by querying the 'data' object in the console. `data.uuid` is equal to the user's `uuid`, which should be the same as `uuid_driver` or `uuid_rider`, depending on their type.

**Comment by sasjkia** [comment]
thanks @richardwestenra. so, is the page you sent meant for drivers or riders? just trying to understand what each button means?

**Comment by sasjkia** [comment]
@richardwestenra do any of these buttons work irl? will the phone operator be able to use them on behalf of riders/drivers?

**Comment by jkbits1** [comment]
what is the spec being used to create the self service page, please? I don't mean the user stories spec which contains the API that I have already built. I've seen a couple of proposal specifications for this page over the last few days, but I need to know which one has been agreed on.

If I have a clear idea of what we want to build, then I can create an API to suit that, and provide at least some of the functionality required. We really need to agree on something here, there is so little time left in which to make useful progress. If I'm asking the wrong questions for some reason (this isn't my first time of asking) do please let me know

**Comment by jkbits1** [comment]
when I created the original prototype of the self service page I tested the functionality of all the API calls. It was possible to make ajax calls in the front-end (I had to mock the data being given to the page). These connected to the API of my node app and executed the db code. These successfully set the state of the fields in the db and caused sms messages (and presumably emails) to be sent. 

That db code (with some of my changes since) and the node app still work in my own tests.

**Comment by sasjkia** [comment]
@jkbits1 sorry about any misunderstanding. I'd like to understand what you need from me. is it different to this: https://docs.google.com/document/d/1qDxBiC8ZKRubneuzDO6_eu9tf1BNX09zwcfZYZs-KxU/edit?usp=sharing

**Comment by richardwestenra** [comment]
The best selfservice spec I've seen so far is [this wireframe](https://github.com/misteranderson/my.carpoolvote/tree/master/Ideas) by @misteranderson. We need something akin to the api.carpoolvote.com/{live}/signin/ endpoint/.

**Comment by jkbits1** [comment]
@richardwestenra @sasjkia thank you both for getting back to me :+1:  :smile: I'm not sure if you've seen each other's comments but you have each referred to a different document. At first glance, they are similar but I remember mr anderson saying he has a different take on things.

Which document should I use? I can get involved in a discussion if necessary, that's fine. To deliver something, I'll definitely have to change, test and redeploy the node app. It may also need new db code. It's going to be hard to change direction too much once I begin :smile:

**Comment by sasjkia** [comment]
@jkbits1 - @misteranderson's version works, thanks! :)

**Comment by jkbits1** [comment]
@sasjkia @richardwestenra great, I'll see what I can do over the weekend

**Pull request merged**
