### PR TITLE
Vote dropdown #37

### PR DESCRIPTION
**Pull request by dbrusky1**
Deleted "Are you registered link".  Added Dropdown of states with link to stat voting registration site.

Also  integrated #38 changes.  All text and images from mockup, changed title, and incorporated dropdown.

### CODE REVIEW

**Comment by sasjkia** [comment]
Thanks for doing these @dbrusky1. When I open index.html in the browser, I can't see the drop-down

**Comment by sasjkia** [comment]
@dbrusky1 once this is working, code could also be reused for issue #50

**Comment by dbrusky1** [comment]
sasjkia, if you drag the file or open it form the menu bar it will cause an error(cross-origin), because I'm using ajax to serve the data.  I am viewing it through node-server....if you install node on your computer and then you can serve any file by going into that folder and typing "http-server".  
https://github.com/indexzero/http-server

**Comment by sasjkia** [comment]
This is great, @dbrusky1 ! Well done!

**Comment by sasjkia** [comment]
Would you mind creating a small change? Could "Am I registered" be in the style of a headline, same as "Need further support?"

**Pull request merged**
