### PR TITLE
Merge 'develop' branch into 'master'

### PR DESCRIPTION
**Pull request by richardwestenra**
## Description

The 'develop' branch (mostly built by @thisisjofrank, I believe) is version 2 of the site. It was based on the updated designs posted on Slack. 

I've got a working demo of this branch up at http://richardwestenra.com/voteamerica.github.io/.

I have been working on my own separate 'merge-develop' branch to fix conflicts and get this work merged into master. It's not perfect yet, but I want to get it merged asap so we can cut down on the number of divergent versions of the site.

## Changelog

I've kept the form HTML, footer scripts, and most of the body content from master. Meanwhile, I've  copied the header, body content, and new CSS from develop. I've also added a few of my own changes, e.g. adding [Salvattore.js](http://salvattore.com/) in order to get the body content grid layout to work nicely, as the existing flexbox layout wasn't really working.

The new develop styling is intended to work *without* Bootstrap, however because I was trying not to change the form HTML in any way, I have kept Bootstrap in for the time being so that the form layout remains mostly intact. Once it's merged, I plan to remove Bootstrap again and update the form styling myself.

## QA

@sasjkia Can you please let me know whether you have any urgent changes to add before this is merged?
@dmilet Can you please doublecheck that I haven't broken the form connection to the backend?

## Deployment notes

Once this has been deployed, we can close the 'develop' branch.

### CODE REVIEW

**Comment by sasjkia** [comment]
@richardwestenra thanks so much for your efforts on this! i have no urgent changes before this gets merged. :)

**Comment by sasjkia** [comment]
just had another look and we don't need the "why are we doing this" box, as it repeats the one above

**Comment by dmilet** [comment]
@richardwestenra I looked at the diff for index.html, and it seems good to go. All changes are related to styling it seems, nothing related to the names of the input elements. So, OK for the backend.
I don't have time now to into the details of it. If you want to have this merged, I'd say let's go. I can do it, or you can too.

**Comment by sasjkia** [comment]
Rider form does still need a notes box for disability accommodation input.

**Comment by richardwestenra** [comment]
Cool, thanks pals. 

Sasjkia it sounds like that's an unrelated merge conflict issue from earlier that I missed, so it can be resolved in a separate PR. It might be worth creating an issue to document any regressions that still need to be fixed/reimplemented.

I'm gonna go ahead and merge now.

**Pull request merged**
