### PR TITLE
Form JS updates

### PR DESCRIPTION
**Pull request by richardwestenra**
## Description

- Fix zip code validation (fixing issue #101)
- Make the legal checkboxes required
- Move Moment.js script tag to the end of the page, and also remove commented-out bootstrap link, and remove duplicate bootstrap validator script tag.
- Major form submission JS refactor/simplification 😃
- Make the legal checkboxes required (cc @sasjkia)

## Development notes:
I've managed to simplify the form JS a lot by generalising the behaviour, and by saving the date/time data to the button using `jQuery.data()`, then joining it on submit. I hope this works! ✌️

### CODE REVIEW

**Comment by jkbits1** [comment]
this looks great to be merged after the demo. there is now date/time handling for both riders and drivers. The various form submissions may have minor differences now

**Comment by jkbits1** [comment]
taking a quick look at the code for addTimeBtnListener, the existing mechanism stores the start/end ISO fields in list items in a different `<ul>` depending on what is passed as the `$timesList` param. If we do refactor to the `$(this).data()` approach it would be good to retain this separation / information. Let me know if that explanation is unclear :smile: 

I don't want to hold up merging this PR though, it has very important stuff in it and closes some issues

**Comment by richardwestenra** [comment]
@jkbits1 Thanks Jon. If I understand you correctly, you want to be sure that the information is stored separately for each form? If so, great because that should still be the case :). This PR merely changes things so that the data is bound to the `.add-time-btn` element with `jQuery.data()` instead of attaching it the the `<ul>` using HTML attributes. They should still be separate.

As for the data stored: It's currently only saving `isoStart` and `isoEnd` (after joining them with a `/`). I considered saving all the extra data as well, but I decided not to because `isoStart` and `isoEnd` are the only data-points that are being sent on form submission, as far as I could tell. If we need more data then I could easily change it to something like this:
```
var data = $(this).data('datetimes') || [];
// data.push( [isoStart, isoEnd].join('/') );
data.push({
	timeId: timeId,
	date: date,
	niceDate: niceDate,
	startTime: startTime,
	endTime: endTime,
	isoStart: isoStart,
	isoEnd: isoEnd,
	isoTimeStamp: [isoStart, isoEnd].join('/')
});
$(this).data('datetimes', data);
```
This way we could save/send as much time data in as many different formats as we like.

**Comment by jkbits1** [comment]
@richardwestenra that sounds fine about the data being stored separately for each form. I don't know the specific purposes of the other data items. some is for the UI and the rest presumably was intended for what the latest code is doing, but I can't tell which is which without reading the code more. Your refactored code stores all the data that concerns iso dates, no need to store anything else for that.

another demo is on later today, so I'll double-check locally then merge :+1:

**Comment by jkbits1** [comment]
@richardwestenra there's a minor issue when no date-time objects are selected. the form submission code fails when attempting to join an undefined object. This leads to empty object braces being stored in the db rather than an empty string. Presumably we want to prevent that but we don't at the moment.

When testing, I've also spotted a bug with my iso generation. As it might be awkward to co-ordinate the two fixes (and demo later) I'll merge this and patch both now

**Comment by jkbits1** [comment]
@richardwestenra thanks :+1:

**Pull request merged**
