### PR TITLE
Add legal tick boxes to I NEED A RIDE form.

### PR DESCRIPTION
**Pull request by GregSaintJean**

### CODE REVIEW

**Comment by sasjkia** [comment]
Perfect - now just change "driver" to "rider" in I CAN OFFER A RIDE. And then add the bit about driver license number. Thanks!!!

**Comment by sasjkia** [comment]
Oh sorry - didn't see vehicle reg at the bottom. Pls could this be underneath insurance details request? Also, could all the legal bits pls be forced entry?

**Comment by GregSaintJean** [comment]
What do you mean by forced entry?

**Comment by sasjkia** [comment]
The user has to fill them in to complete the form

**Comment by GregSaintJean** [comment]
O I see so verify that certain items are filled in before submitting. Stop the user if they aren't. Besides the legal bits, the rest of the form probably also needs to be verified right? Not everything, but certain particular items?

**Comment by sasjkia** [comment]
Yes. I've tested and seems it's only the legal bits that still need this. I forgot to test the name/email/phone number bits because those populated automatically.

For drivers, email should be compulsory. For riders, email is optional but phone number compulsory (some riders may have low connectivity - so we don't want to exclude them with this measure)

**Pull request merged**
