### PR TITLE
Update T&Cs checkboxes and add new How it Works page

### LINKED ISSUE #153: Create "How it works" page
- [x] Please create a new page containing instructions on how to use the platform. On this page, please include Riders and Drivers instructions in 2 side-by-side columns.
- [x] Link to this page from the "How it works" hyperlink at the top of the home page. The "How it works" link should no longer point to a different section on the home page.

**How does Carpool Vote work?**

Carpool Vote connects volunteer drivers with anybody who needs a ride to claim their vote.

Anybody can sign up to get a ride or to drive somebody: We welcome humans of any race or ethnicity, age, sex or gender identity, sexual orientation, disability status, family situation, or religious or political belief.

_Riders_
Need a ride to claim your vote? Some of our riders need to get to the polls - either on polling day or during early voting. Others need to travel to get a photo I.D.

Whatever your situation, simply click the [link: I NEED A RIDE] button on the CarpoolVote.com home page and fill in your details.

You’ll receive a message straight away confirming that we’ve received your request.

Our system will then match you with a driver, based on the information you’ve provided. This match will be based on when and where you need a ride, for how many people, and disability adjustments you may need.

You’ll receive another message as soon as you’ve been matched. The driver will receive a similar email, including your contact information.

The driver will then contact you directly to arrange the details of the ride.

Please follow the instructions in our messages if you need to view or manage your ride request or your match with a driver. You can also use our online self-service portal: http://www.carpoolvote.com/self-service/

_Drivers_
Do you believe that every American deserves a vote? Why not turn this passion to action and become a volunteer driver? Sign up to give a fellow American a ride to the polls on Election Day. Or, if there is early voting in your state, let us know if you can help a little earlier. Alternatively, if you live in a state where you need to show voter I.D. at the polls, you could drive somebody to go and get one.

You can sign up to give a ride by selecting the [link: I CAN OFFER A RIDE] button and filling in your details.

You’ll receive a message straight away confirming that we’ve received your offer.

Our system will then match you with riders, based on the information you’ve provided. This matches will be based on when, where, and how many people you can drive, and whether you have a powerchair-adapted vehicle.

You’ll receive a message for each proposed match, including the details of the ride request. you can accept any ride requests that work for your schedule. Once you have accepted a ride request, we’ll send you another message letting you know how to get in touch with your rider. The rider will receive a similar message, including your contact information.

It is then up to you to contact the rider to arrange the details of the ride.

Please follow the instructions in our messages if you need to view or manage your ride offer or your matches with riders. You can also use our online self-service portal: http://www.carpoolvote.com/self-service/

### LINKED ISSUE #161: Add terms and conditions
Use terms and conditions in the following document: https://docs.google.com/document/d/1ouu7DBSgAP2RBK93hnHX0YIY45oVopyxVriEtrE3KYA/edit?usp=sharing
- [x] Create a separate page that contains the terms and conditions
- [x] Create a link in the bottom-right of the footer on the home page that links to the Terms and Conditions
- [x] On the DRIVER and RIDER signup forms, add statement with check box: "I agree to the Terms and Conditions", right above "We'd like to keep you updated..." Checkbox.
  Underneath this statement, include - as part of the same single check box but in three separate paragraphs - the three statements that were previously three separate checkboxes ("I understand that Carpool Vote will share my contact details...", "I understand that Carpool Vote provides introductions between riders...", "I understand that this service is open to any driver or rider...").
  Underneath these paragraphs, add a link to the Terms and Conditions page.
- [x] Change all mentions of "Carpool Vote" in the T&C's to "Carpool Vote LLC".

### PR DESCRIPTION
**Pull request by richardwestenra**
This PR is based on #187 by @moinshaikh. I fixed the merge conflict and cleaned up some of the code. It fixes #153 and fixes #161.

T&C boxes:
image

New How it Works page:
image

### CODE REVIEW

**Comment by sasjkia** [comment]
looks good to meeee!!!

**Comment by richardwestenra** [comment]
lol, thanks @sasjkia. Good enough for me ;) - I'm gonna merge.

**Comment by misteranderson** [comment]
What about impacts to backend?  Is there an associated PR there?

**Comment by richardwestenra** [comment]
Good point. I assume that this won't affect the back end, but tbh I never thought to check. @misteranderson @dmilet @jkbits1 are there likely to be any side-effects due to removing the `RiderWillBeSafe`, `RiderWillNotTalkPolitics`, `RiderLegalConsent`, `RidersCanSeeDriverDetails`, `, `DriverWillTakeCare`, and `DriverWillNotTalkPolitics` checkboxes? afaik they're not actually used for anything on the back end, right?

**Comment by jkbits1** [comment]
@richardwestenra the problems happen when data is mandatory in the db and it's not provided. What happened in testing against the test system?

**Pull request merged**
