### PR TITLE
Visitor Update

### PR DESCRIPTION
**Pull request by christiansantos647**
Add update for visitors to site

### CODE REVIEW

**Comment by jkbits1** [comment]
@christiansantos647 thanks for this 👍 it looks great. I'll review it fully later

**Comment by jkbits1** [comment]
@christiansantos647 I've just reviewed this and it's really good, thank you 😄 

What would make it even more effective is to add a few styles to the enclosing `header` element, to move the text away from the browser edge and make the font larger. In my own test environment, I tried adding the following styles to the header element with the browser devTools inspector (there's no need for you to be familiar with the inspector, though) and that seemed to look reasonable.

```
text-align: center;
font-weight: bold;
font-size: 18px;
padding: 20px;
```

How do you feel about adding some styles, whether these suggestions or something else? It's fine to add them inline as `<header ... style="...your styles here...">` as that may be easier than changing the css file.

Does that sound ok? If not, no problem, I'll merge your PR and apply some styles myself. Just let me know what you prefer.

**Comment by jkbits1** [comment]
@christiansantos647 I've merged this PR as it is, and will add some styles similar to those above. Thanks again! 👍

**Comment by christiansantos647** [comment]
Hi, sorry for the late reply. I will try to add some more to the repository
in the future if I have time. Thank you for merging! It's my first time
committing to a repository and I had a bit of trouble going through
everything.

**Comment by jkbits1** [comment]
@christiansantos647 no worries about the late reply and I was very happy to merge your contribution (it's live on the site now), it's very helpful. I'm really pleased to hear it was your first PR, we all remember how difficult that was for us, too 😄 Kent C Dodds, a well-known programmer, has blogged about his first contribution.

Everything you did was fine, and it's normal to have a discussion like ours for most PRs. Welcome to open-source!

**Pull request merged**
