### PR TITLE
Fix thanks redirect URL query string bug

### LINKED ISSUE #198: Driver Thanks page does not link to self-service page correctly
When the self-service page is accessed from the Driver Thank you page, the wrong param is sent (uuid, not UUID_driver). The confirmation field is shown but there is not Login button.

The self service page is not usable

I'm assuming these things are connected but happy to help resolve the issue whatever the cause

### PR DESCRIPTION
**Pull request by richardwestenra**
- Make T&C checkboxes required and make the names/IDs unique
- Fix self-service redirect QS bug (fixes #198 and resolves #209).

### CODE REVIEW

**Comment by richardwestenra** [comment]
Please forgive me @jkbits1 but I'm going to merge this myself, because it's already not working so it can't really hurt. I think this will fix things but we'll just have to wait and see.

**Comment by jkbits1** [comment]
@richardwestenra merge away, let's get as working functionality in there as we can :smile:

**Comment by jkbits1** [comment]
@richardwestenra from a brief check this resolves the problem with displaying the uuid as dealt with in
https://github.com/voteamerica/voteamerica.github.io/pull/209

Does it also resolve the self service href issue that was addressed in 
https://github.com/voteamerica/voteamerica.github.io/pull/209 ?

**Comment by richardwestenra** [comment]
As far as I can tell from my testing, the href works better now. I've updated http://richardwestenra.com/voteamerica.github.io so we can test it more extensively.

**Pull request merged**
